services:
  dhesinta:
    build: .
    container_name: dhesinta
    restart: unless-stopped
    networks:
      - dhesinta
    volumes:
      - ./db:/app/db
      - ~/.config/dhesinta:/root/.config/dhesinta

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dhesinta
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  dhesinta:
